#ifndef ALGORITHM_ENUMS
#define ALGORITHM_ENUMS
enum class Algorithm { BUBBLE, SELECTION, QUICK_ITERATIVE, BOGO, QUICK, DUMMY };
enum class WindowEvent { CLOSE_WINDOW, REGENERATE_VECTOR, NEXT_ALGORITHM, NO_EVENT };
#endif
